name: Monthly Shrimp Imports Ingest

on:
  schedule:
    # run 7th of month at 12:15 UTC (tweak if needed)
    - cron: "15 12 7 * *"
  workflow_dispatch: {}

jobs:
  ingest:
    runs-on: ubuntu-latest
    env:
      CENSUS_API_KEY: ${{ secrets.CENSUS_API_KEY }}
      # how many months of history to pull (default 96 = 8 years)
      SHRIMP_MONTHS_BACK: "96"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ingestion
        run: |
          # you can also pass an explicit number of months, e.g. 96
          python services/census/ingest_shrimp.py

      - name: Commit updated datasets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add database/processed/shrimp_imports.csv database/raw/shrimp_imports/*.csv || true
          git commit -m "chore(data): update shrimp imports dataset" || echo "No changes to commit"
          git push origin HEAD:main || echo "Push failed (maybe branch protection)"